# Intro to Numpy

In [1]:
import numpy as np

### Create arrays in numPy

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
Lista = [3,4,5]

In [5]:
a2 = np.array(Lista)

In [6]:
print("esta es una lista {}, este es un array{}".format(Lista, a2))

esta es una lista [3, 4, 5], este es un array[3 4 5]


In [7]:
result = Lista*2

In [8]:
result

[3, 4, 5, 3, 4, 5]

In [9]:
result2 = a2*2

In [10]:
result2

array([ 6,  8, 10])

In [12]:
type(a2)

numpy.ndarray

### Matrices

In [14]:
matrix = np.array([[1,2,3],[4,5,6]])

In [15]:
matrix.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

### Built-in Functions in NumPy

In [17]:
a3 = np.arange(0,5)

In [18]:
a3

array([0, 1, 2, 3, 4])

In [19]:
a4 = np.arange(0,41,2)

In [20]:
a4

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40])

In [23]:
Z = np.zeros((10,7))
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [24]:
Ones = np.ones(4)
print(Ones)

[1. 1. 1. 1.]


In [27]:
I = np.eye(3,3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Linspace

In [28]:
np.linspace(0,3,10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

### Random data

In [29]:
np.random.rand(5)

array([0.7879752 , 0.55378815, 0.9753687 , 0.86344203, 0.3334292 ])

In [30]:
np.random.randint(1,50,10)

array([24, 49, 15, 38, 17, 32, 34, 31, 19, 39])

In [36]:
np.random.randn(3,30)  #from a normal distribution

array([[ 1.27359544, -2.6831074 ,  0.15688638, -0.91658614, -0.81025013,
        -1.0590104 ,  1.17269587,  0.25653732, -0.8006962 , -2.02284095,
        -0.18329558,  1.62378592,  0.55499022,  0.20772016, -0.21406979,
         0.45140532,  0.5123543 , -0.92032969,  1.27557437,  0.23954596,
        -0.1929119 , -1.13433912, -0.25179679,  1.62921214,  1.14381378,
        -0.8996072 , -1.16951609, -1.42357858, -0.66498537,  0.01950568],
       [ 0.49734894,  0.08871314, -0.59191481, -2.06163856, -0.92593764,
        -0.48897162, -0.49003384,  0.54524655,  0.70484426, -1.22785722,
         0.4745699 , -1.33517732,  0.37789078,  0.83551706,  0.03011514,
         1.06703119,  0.49606274,  0.61607389, -0.96103939,  0.31725868,
         0.26086988, -3.5798253 ,  0.27199315,  1.34943179,  2.40069972,
        -2.16151307, -1.20674542,  0.16664379, -2.37530382, -0.99950533],
       [ 0.84394631,  0.0353271 , -0.08723174, -1.02576875, -2.5015081 ,
        -0.0676641 , -0.58896864, -0.09235252,  0

In [31]:
np.random.randn(20)  #from a normal distribution

array([ 0.02218459,  0.08880571,  0.92770353,  0.11844932,  0.57630789,
        0.85508981, -1.10510527,  0.14967649,  0.66505324,  0.76264378,
        0.47833834,  1.17500651, -1.48281492, -0.26521501, -1.10373867,
        1.28746189,  1.01046585,  0.34429862, -0.05867224,  1.36258863])

### Arithmetic

In [34]:
print(a2)
a2.shape

[3 4 5]


(3,)

In [35]:
I.shape

(3, 3)

In [37]:
a2.min()

3

In [38]:
a2.max()

5

In [39]:
a2.argmax()

2

In [40]:
a5 = np.array([1,2,3,3,2,0])

In [42]:
a5.argmax() #Index of the first max found

2

In [ ]:
a5.ss